### ISSUE TITLE
R Ladies Reprex

### ISSUE THREAD

**Issue by yeelauren** [emitanaka/anicon#8]
Hi Emi!
Here is my reprex:

```

---
title: "Presentation Ninja"
subtitle: "⚔<br/>with xaringan"
author: "Yihui Xie"
institute: "RStudio, PBC"
date: "2016/12/12 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


class: middle center 


# Introduction to R 
## Session 1
### July 14 th, 2020
### `r anicon::faa('twitter', animate='float')` 
### `r anicon::faa('envelope', animate='pulse', speed='slow', colour='black', rtext=' beep beep')` 

```

```
 sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252
[4] LC_NUMERIC=C                    LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.5.0  reprex_0.3.0

loaded via a namespace (and not attached):
 [1] xfun_0.21           bslib_0.2.4         remotes_2.1.1       testthat_3.0.1      vctrs_0.3.6        
 [6] usethis_1.6.1       miniUI_0.1.1.1      htmltools_0.5.1.1   yaml_2.2.1          rlang_0.4.10       
[11] pkgbuild_1.0.8      jquerylib_0.1.3     pillar_1.4.4        later_1.1.0.1       glue_1.4.2         
[16] withr_2.4.1         sessioninfo_1.1.1   lifecycle_0.2.0     stringr_1.4.0       devtools_2.3.0     
[21] evaluate_0.14       memoise_2.0.0       knitr_1.31          callr_3.5.1         fastmap_1.0.1      
[26] httpuv_1.5.4        ps_1.5.0            fansi_0.4.1         Rcpp_1.0.4.6        xtable_1.8-4       
[31] clipr_0.7.0         readr_1.4.0         xaringanExtra_0.2.6 backports_1.1.7     promises_1.1.1     
[36] cachem_1.0.1        desc_1.2.0          pkgload_1.1.0       jsonlite_1.7.2      mime_0.10          
[41] fs_1.4.1            servr_0.21          hms_0.5.3           packrat_0.5.0       digest_0.6.25      
[46] stringi_1.4.6       xaringan_0.19       processx_3.4.5      rprojroot_1.3-2     anicon_0.1.0       
[51] cli_2.2.0           tools_4.0.2         magrittr_2.0.1      sass_0.3.1          tibble_3.0.5       
[56] crayon_1.3.4        whisker_0.4         pkgconfig_2.0.3     ellipsis_0.3.1      rsconnect_0.8.16   
[61] prettyunits_1.1.1   assertthat_0.2.1    rmarkdown_2.7       rstudioapi_0.11     R6_2.5.0           
[66] icon_0.1.0          compiler_4.0.2 
```
